const activities = [{
    key : "Arts and Culture",
    img : "https://ucarecdn.com/48ce5d34-f8f0-4e35-a4f7-e68c7057cb4c/"
    // "Astronomy",
    // "Auto and ATV",
    // "Biking",
    // "Boating",
    // "Camping",
    // "Canyoneering",
    // "Caving",
    // "Climbing",
    // "Compass and GPS",
    // "Dog Sledding",
    // "Fishing",
    // "Flying",
    // "Food",
    // "Golfing",
    // "Guided Tours",
    // "Hands-On",
    // "Hiking",
    // "Horse Trekking",
    // "Hunting and Gathering",
    // "Ice Skating",
    // "Junior Ranger Program",
    // "Living History",
    // "Museum Exhibits",
    // "Paddling",
    // "Park Film",
    // "Playground",
    // "SCUBA Diving",
    // "Shopping",
    // "Skiing",
    // "Snorkeling",
    // "Snow Play",
    // "Snowmobiling",
    // "Snowshoeing",
    // "Surfing",
    // "Swimming",
    // "Team Sports",
    // "Tubing",
    // "Water Skiing",
    // "Wildlife Watching"
  }]

  export default activities